### PR TITLE
Modify the structure of scheduling

### PR DESCRIPTION
**Pull request by wangch079**
## Part of https://github.com/elastic/enterprise-search-team/issues/4628

This PR modifies the structure of `scheduling`, to accommodate different types of scheduling.

#### Pre-Review Checklist
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Review by artem-shelkovnikov — APPROVED** [review]
LGTM - might be worth to add logic that also checks if any other type of schedule is there and shows error/warning that schedule other than full is not supported

**Comment by wangch079** [comment]
> LGTM - might be worth to add logic that also checks if any other type of schedule is there and shows error/warning that schedule other than full is not supported

We don't have this kind of validation in python either. We can't prevent users from adding something funny as we don't enforce strict mapping, but I think it's fine because we only care about `full`, `incremental` and `permissions`.

**Comment by artem-shelkovnikov** [comment]
> We don't have this kind of validation in python either. We can't prevent users from adding something funny as we don't enforce strict mapping, but I think it's fine because we only care about full, incremental and permissions.

What I mean is that Ruby won't support even incremental/permissions, so if someone decides to use MongoDB in Python and then switches to Ruby it'll be a legit case that Ruby does not support and might be worth to communicate to user.

**Comment by wangch079** [comment]
>so if someone decides to use MongoDB in Python and then switches to Ruby it'll be a legit case that Ruby does not support and might be worth to communicate to user.

🤔 Mmm... is it even a valid use case? we are not supporting Ruby connectors anymore. We made this PR to support Crawlers, not connectors.

**Comment by artem-shelkovnikov** [comment]
> 🤔 Mmm... is it even a valid use case? we are not supporting Ruby connectors anymore. We made this PR to support Crawlers, not connectors.

Not sure, just wanted to double check with you how you feel about it

**Comment by wangch079** [comment]
>Not sure, just wanted to double check with you how you feel about it

I think the only reason we make some changes to `connectors-ruby`, is either 1) there's severe vulnerability or 2) there's breaking changes to crawler(I'm not even sure about point 1).

If the scheduling structure change doesn't affect crawler, I don't think I will make this PR, even though it means `connectors-ruby` won't work with Elasticsearch and Enterprise Search 8.9. Because we are not releasing any new versions (surprisingly to see we still have 8.8 branch)

**Pull request merged**
