### PR TITLE
Remove analyzer settings for content index

### PR DESCRIPTION
**Pull request by wangch079**
Remove the analyzer settings for the content index from the connector service, which should be set by Kibana when the index is created.

#### Pre-Review Checklist
- [ ] Covered the changes with automated tests
- [x] Tested the changes locally

### CODE REVIEW

**Review by wangch079 — COMMENTED** [review]
I intentionally keep [text_analysis_settings.rb](https://github.com/elastic/connectors-ruby/blob/main/lib/utility/elasticsearch/index/text_analysis_settings.rb) and [language_data.yml](https://github.com/elastic/connectors-ruby/blob/main/lib/utility/elasticsearch/index/language_data.yml).

CLI allows operators to create connectors (but it won't create the content index for now), and those files are needed when the backend needs to create the content index.

**Review by artem-shelkovnikov — APPROVED** [review]
LGTM, minor concern - it can break the creation of connectors via CLI and it's not yet possible to test it without https://github.com/elastic/connectors-ruby/pull/218

**Comment by wangch079** [comment]
> LGTM, minor concern - it can break the creation of connectors via CLI and it's not yet possible to test it without #218

For now, `the creation of connectors via CLI` doesn't create the content index. That's why I want to keep the 2 files not in use for now, as mentioned in https://github.com/elastic/connectors-ruby/pull/216#pullrequestreview-1052278795

**Comment by seanstory** [comment]
@wangch079 this was merged to `main` but not backported to `8.4`. But the label is v8.4.0. Does this need a backport?

**Comment by vidok** [comment]
@wangch079 is there any GitHub issue or other references for this change?

**Comment by wangch079** [comment]
> @wangch079 is there any GitHub issue or other references for this change?

No. I just linked the slack discussion in the description of the PR.

**Pull request merged**
