### PR TITLE
[8.5] Connector service documentation (#367)

### PR DESCRIPTION
**Pull request by wangch079**
# Backport

This will backport the following commits from `main` to `8.5`:
 - [Connector service documentation (#367)](https://github.com/elastic/connectors-ruby/pull/367)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Comment by danajuratoni** [comment]
Looks good. 
One minor improvement would be to add a table of contents for files longer than 1 average screen e.g. DEVELOPING.md, but this is not a blocker.

**Comment by wangch079** [comment]
Hi @danajuratoni , this is a backport PR 😅

**Comment by leemthompo** [comment]
@wangch079 that was a test to make sure you were paying attention 😜

**Review by tarekziade — APPROVED** [review]
LGTM

**Pull request merged**
